# GA Data Science 19 (DAT19) - Class 5
## Developing Mastery of Pandas, Numpy & Bokeh
####  

Justin Breucop (with parts from Craig Sakuma)

## Lab goals

- NumPy: Entering the Matrix
- Pandas: DataFrames as Bamboo
- Bokeh: Picture-Perfect Visuals

##NumPy
As we've seen in lecture, linear algebra is the branch of mathematics describing navigation between different vector spaces. This core concept is very important as a big piece of data cleansing is converting data into various formats and certain algorithms require data to be in a specific shape.

NumPy is a package designed to be used in scientific computing, and specifically around building N-dimensional array objects.

###Creating an array

In [2]:
import numpy as np
a = np.arange(25).reshape(5,5)
# arange(n) is a function that creates a 1 row array of integers of length n 
# reshape(M,N) is a method converts a list to a matrix of size MxN
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

We can convert from lists to arrays. Note however unlike lists, elements of an array all have to be of the same datatype.

In [3]:
alist = [[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24]]
type(alist)

list

In [4]:
np.array(alist)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
biga = a*10
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [6]:
print biga.mean()
print biga.mean(0) #Average per column
biga.mean(1) #average per row
# type(biga.mean(1))

120.0
[ 100.  110.  120.  130.  140.]


array([  20.,   70.,  120.,  170.,  220.])

In [7]:
bigm = np.matrix(biga-20)
bigm

matrix([[-20, -10,   0,  10,  20],
        [ 30,  40,  50,  60,  70],
        [ 80,  90, 100, 110, 120],
        [130, 140, 150, 160, 170],
        [180, 190, 200, 210, 220]])

In [8]:
np.linalg.inv(biga-20)

array([[ -2.81474977e+13,  -1.52777778e-03,   5.62949953e+13,
         -2.22222222e-02,  -2.81474977e+13],
       [  3.51843721e+13,   2.25000000e-02,  -5.27765581e+13,
         -3.51843721e+13,   5.27765581e+13],
       [ -4.22212465e+13,   9.38249922e+13,  -7.97512434e+13,
          4.69124961e+13,  -1.87649984e+13],
       [  9.14793674e+13,  -1.87649984e+14,   9.26521798e+13,
          1.17281240e+13,  -8.20968682e+12],
       [ -5.62949953e+13,   9.38249922e+13,  -1.64193736e+13,
         -2.34562481e+13,   2.34562481e+12]])

####Slices

In [9]:
bigm = np.array(bigm)
bigm[0]

array([-20, -10,   0,  10,  20])

In [10]:
#Same thing, but demonstrating the full slice with a colon
biga[0,:]
biga

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240]])

In [11]:
biga[:,3]

array([ 30,  80, 130, 180, 230])

Slice rules work for even more complex dimensional data

In [12]:
compa = np.arange(30).reshape(5,3,2)
compa

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [13]:
# lets describe it
print compa.shape
print compa.ndim
print compa.dtype

(5, 3, 2)
3
int64


In [14]:
compa[3,:,1]

array([19, 21, 23])

In [15]:
compa[0,0,0]

0

In [16]:
compa[0,0,0] = 5.9
compa[0,0,0]

5

Numpy tries to resolve conflicting datatypes, sometimes to our dismay

In [17]:
compa = compa.astype(float)
compa[0,0,0] = 5.75
compa[0,0,0]

5.75

####Random Numbers
Random numbers are very helpful and are necessary at times for testing data pipelines and running statistical analyses. Functions for creating random values are under numpy.random.

In [18]:
#Create a randomized array
rm = np.random.rand(5,5)
rm

array([[ 0.06226641,  0.95665135,  0.46827399,  0.2427112 ,  0.47434172],
       [ 0.18247737,  0.60976041,  0.46734913,  0.64480892,  0.24792044],
       [ 0.34452467,  0.88275608,  0.77202249,  0.91734741,  0.02260563],
       [ 0.36348068,  0.91352437,  0.13565747,  0.14893689,  0.72795279],
       [ 0.65599209,  0.73576685,  0.73779775,  0.73088728,  0.54035326]])

In [21]:
rm.shape

(5, 5)

In [24]:
print rm.mean()
print rm.mean(0) #Average per column
print rm.mean(1) #average per row

0.519446667096
[ 0.32174824  0.81969181  0.51622017  0.53693834  0.40263477]


In [25]:
# for a different Normal Distribution, use np.random.normal
rm = np.random.normal(5,9,(30,30))
rm

array([[  8.80656027e-01,  -3.45223416e+00,   9.66394315e+00,
         -1.37379422e+01,  -7.17104416e-01,   2.33143985e-01,
          6.63507034e+00,   5.99998456e+00,  -9.20698490e+00,
         -7.82286985e+00,  -3.98236711e+00,  -9.85569637e+00,
         -8.43791861e-01,   5.89656478e+00,   5.76624484e+00,
          2.37108282e+01,  -7.48748129e-01,   3.80661130e+00,
         -1.24478972e+01,   1.72016606e+01,  -2.72753249e+00,
          6.68919423e+00,   3.69006599e+00,   1.49038037e+00,
         -6.23376543e+00,  -5.42336508e+00,   1.02099451e+01,
          6.45077724e+00,   1.64840206e+01,  -2.05880211e+00],
       [ -1.25273851e+01,   3.47593194e+00,   4.93660292e+00,
          1.03447283e+01,   2.05065583e+01,  -1.98459660e+01,
          1.20177606e+01,   1.21003742e+01,   1.08443901e+01,
          6.53994814e+00,  -2.64320733e+00,   2.85659060e+01,
          6.99913154e-01,   3.38643046e+00,   1.13306531e+01,
         -3.99077806e-01,  -1.07736023e+01,  -6.70780661e+00,
       

In [26]:
print rm.mean(), "which is hopefully close to the input mean"
print rm.var(), "which variance = stdev squared"
print np.median(rm)

4.72380506608 which is hopefully close to the input mean
88.3426559497 which variance = stdev squared
4.64029097466


Find more distributions and random functions here: http://docs.scipy.org/doc/numpy/reference/routines.random.html

###Exercise 1
1) Create a 4x5 array of integers numbering 0 to 19.

In [ ]:
np.arange(20).reshape(4,5)

2) Create a 50x500 array with a mean of 20 and variance of 100. Save it to a variable called  `biggie`

In [1]:
biggie = np.random.normal(20,10,(50,500))
print biggie.shape
print biggie.mean()
print biggie.var()

NameError: name 'np' is not defined

3) Change the mean of the array to a value within 1 of 0 and the variance within 1 of 25. Think about what the mean and the variance represent and try using various mathematical operations.

In [ ]:
morph = (biggie - 20)/2
print morph.mean()
print morph.var()

##Pandas: DataFrames as Bamboo
You've already been exposed to dataframes in the previous labs so lets get into dataframes and how we can work with them.

In [28]:
import pandas as pd

#data = pd.read_csv("../data/titanic.csv")
data = pd.read_csv("../data/titanic.csv")
data.head()
#data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex  Age  SibSp  \
0                            Braund, Mr. Owen Harris    male   22      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                             Heikkinen, Miss. Laina  female   26      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                           Allen, Mr. William Henry    male   35      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [29]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [43]:
#data[data.Age>65] #declaring a mask
#data[data.Age>65]
data['Test']=data.Age
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   22      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1   
2                               Heikkinen, Miss. Laina  female   26      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1   
4                             Allen, Mr. William Henry    male   35      0   
5                                     Moran, Mr. James    male  NaN      0   
6                              McCarthy, Mr. Timothy J    male   54      0   
7                       Palsson, Master. Gosta Leonard    male    2      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female   27      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female   14      1   
10                     Sandstrom, Miss. Marguerite Rut  female    4      1   
11                            Bonnell, Miss. Elizabeth  female   58      0   
12                      Saundercock, Mr. William Henry    male   20      0   
13                         Andersson, Mr. Anders Johan    male   39      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female   14      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female   55      0   
16                                Rice, Master. Eugene    male    2      4   
17                        Williams, Mr. Charles Eugene    male  NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female   31      1   
19                             Masselmani, Mrs. Fatima  female  NaN      0   
20        

In [40]:
data[(data.Age==11)&(data.SibSp==5)]

PassengerId  Survived  Pclass                                Name   Sex  \
59           60         0       3  Goodwin, Master. William Frederick  male   

    Age  SibSp  Parch   Ticket  Fare Cabin Embarked  
59   11      5      2  CA 2144  46.9   NaN        S

In [ ]:
data[(data.Age==11)|(data.SibSp==5)]

###Cleaning Data

In [ ]:
data.info()

####Working with nulls
Exclude data

In [ ]:
# data[data.Age.isnull()]
data[data.Age.notnull()]

In [ ]:
# You can also just replace the nulls
data.Age[data.Age.isnull()].fillna(0)

In [ ]:
#Replace with the mean to preserve statistical values
avg_age = data.Age[data.Age.notnull()].mean()
print avg_age
data.Age.fillna(avg_age)

####Replace with random normal distribution

In [ ]:
# Get values of mean and standard deviation
data.Age[data.Age.notnull()].describe()

In [ ]:
# Replace null values with 
data.Age.fillna(np.random.normal(29.7,14.5),inplace=True)

In [ ]:
data.Age.fillna(np.random.normal(29.7,14.5)).describe()

###Convert categorical data to numerical

In [ ]:
data.Sex=='female'

In [ ]:
data.rename(columns={'Sex':'Is Female'},inplace=True)
data['Is Female']=data['Is Female']=='female'
data.head()

In [ ]:
# get unique values of Embarked
data.Embarked.unique()

In [ ]:
# replace values with numbers
data.Embarked.replace(['S', 'C', 'Q'],[1,2,3],inplace=True)
data.head()

###Selecting with .loc, .iloc, & .ix

Selecting data in pandas can be tricky. The main takeaway is that .loc looks for index labels, .iloc looks for the integer index position, and .ix can be a mix. 

In [ ]:
df = pd.DataFrame(np.random.randn(6,4),index=list('abcdef'),columns=list('ABCD'))
df

In [ ]:
df.loc['f']

In [ ]:
df.iloc[len(df.index)-1]

In [ ]:
df.A.ix['f'] == df.A.ix[-1]

In [ ]:
cc = list('cookies')
cc[-4]

###Group by

In [ ]:
# Find average age of passengers that survived vs. died
data.groupby('Survived')['Age'].mean()

In [ ]:
# Count number of female passengers
data.groupby('Is Female')['PassengerId'].count()

In [ ]:
data.groupby(['Survived','Pclass'])['PassengerId'].count()

###Apply

In [ ]:


# Convert ticket prices to USD
data.Fare.apply(lambda x: x*1.6)

In [ ]:
data.Name

In [ ]:
data.Name.apply(lambda x: x.split(",")[0])

###Concatenate

In [ ]:
data_first_half = data.iloc[0:10,:]
data_first_half.info()

In [ ]:
data_second_half = data.iloc[10:,:]

remake_data = pd.concat([data_first_half,data_second_half])
remake_data.info()

###EXERCISE 2
1) Replace Pclass numbers with 'First Class', 'Second Class', 'Third Class'

2) What was the average ticket price for survivors vs. dead passengers?

###Bonus!!!
Round all ages to the nearest year using `apply`

##Bokeh: Picture Perfect Visuals

To install Bokeh, go to a terminal and type:

`conda install bokeh` 

Bokeh is built by the same people that created Anaconda (Continuum Analytics) and is designed out of the box for web display, making it nice for creating presentation ready, interactive visuals quickly. Labs in this course will be shown in Bokeh. Checkout http://bokeh.pydata.org/en/latest/docs/quickstart.html#concepts to see some of the range of capabilities.

In [ ]:
from bokeh.plotting import figure, output_notebook,show,vplot
output_notebook()

In [ ]:
import pandas.io.data
import datetime
aapl = pd.io.data.get_data_yahoo('FB', 
                                 start=datetime.datetime(2015, 4, 1), 
                                 end=datetime.datetime(2015, 4, 28))


In [ ]:
# prepare some data
x = aapl.Low
y = aapl.High

# create a new plot with a title and axis labels
p = figure(title="Stock High vs. Low", x_axis_label='Low', y_axis_label='High')

# These are glyphs
p.circle(x, y,size=30,alpha=.5,)
p.line(x,x*y.mean()/x.mean())

# show the results
show(p)

At its core, Bokeh is built up with Plots and Glyphs. Plots are created with the figure keyword and then glyphs are visuals that are added to the visualization. The visuals are scalable, interactive and savable. You can even create vectorized colors.

In [ ]:
# prepare some data
N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = ["#%02x%02x%02x" % (r, g, 150) for r, g in zip(np.floor(50+2*x), np.floor(30+2*y))]

TOOLS="resize,crosshair,pan,wheel_zoom,box_zoom,reset,box_select,lasso_select"

# create a new plot with the tools above, and explicit ranges
p = figure(tools=TOOLS, x_range=(0,100), y_range=(0,100))

# add a circle renderer with vecorized colors and sizes
p.circle(x,y, radius=radii, fill_color=colors, fill_alpha=0.6, line_color=None)

# show the results
show(p)

In [ ]:
p1 = figure(title="Titanic Ages Dead",x_axis_label = 'Age',y_axis_label = 'Count')
#construct the histogram
hist, edges = np.histogram(data.Age[data.Survived==0].values, density=True, bins=50)
#Construct your x axis
x = np.linspace(data.Age.min(),data.Age.max(),100)
#add the bars, scaling the value to the full count of people
p1.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')

p2 = figure(title="Titanic Ages Survived",x_axis_label = 'Age',y_axis_label = 'Count')

hist, edges = np.histogram(data.Age[data.Survived==1].values, density=True, bins=50)
x = np.linspace(data.Age.min(),data.Age.max(),100)
p2.quad(top=hist*len(data.Age), bottom=0, left=edges[:-1], right=edges[1:],line_color='black')


show(vplot(p1,p2))